### ISSUE TITLE
[FUTURE REQUEST] Pushcut als Benachrichtigung

### ISSUE THREAD

**Issue by monza258** [ticaki/DWD-UWZ-NINA-Pushwarnungen-iobroker#13]
Hi, besteht die Möglichkeit Pushcut als Push Option einzubauen? Vorteil wäre man könnte so heim Automationen starten. Zb Rollos absenken oder Heizung steuern. 

Da könnte man sich sogar Bilder einer Wetterkarte mit schicken lassen. 

[Pushcut API](https://www.pushcut.io/webapi.html)

Lg

**Comment by ticaki** [comment]
Hallo, da muß ich passen, ich hab meine eigene Steuerung schon geschrieben. Kann ich dir zur Verfügungstellen ist aber nicht fertig und auch nicht einfach zu konfigurieren.
