### ISSUE TITLE
ZAMG Beispiel im Skript dwd_uwz_nina_script_with_DWDUWZ_inside_Beta.js

### ISSUE THREAD

**Issue by latzi0710** [ticaki/DWD-UWZ-NINA-Pushwarnungen-iobroker#15]
Kann es sein, dass beim Beispiel der ZAMG Koordinaten lat und lon vertauscht sind und das "=" durch ":" ersetzt gehört?
Skript:-Beispiel // Koordinaten [{lat:13.05501,lon:47.80949}, {lat=13.05501,lon=47.80949}, ...].

**Comment by ticaki** [comment]
Ja die Koordinaten sind im gesamten Script vertauscht.
Nein, das sind Objekte in einem Array

**Comment by latzi0710** [comment]
Alles klar, Danke!
Ich hab´s in der Art eingegeben [{lat:47.80949,lon:13.0550}] und der ZAMG-Link hat den korrekten Ort im Ergebnis-JSON
