### ISSUE TITLE
ERROR in Beta4

### ISSUE THREAD

**Issue by monza258** [ticaki/DWD-UWZ-NINA-Pushwarnungen-iobroker#16]
Hi, ich bekomme beim Starten der Beta 4 einen Error code. Ist auf Anhieb ersichtlich, was zum Error führen könnte? 

`
10.1.2022, 21:14:12.328	[info ]: javascript.0 (1034) Stop script script.js.Unwetterwarnungen_BETA
10.1.2022, 21:14:16.326	[info ]: javascript.0 (1034) Start javascript script.js.Unwetterwarnungen_BETA
10.1.2022, 21:14:16.451	[info ]: javascript.0 (1034) script.js.Unwetterwarnungen_BETA: info: Skripts gestartet: ID:4920.297288737423
10.1.2022, 21:14:16.454	[info ]: javascript.0 (1034) script.js.Unwetterwarnungen_BETA: registered 0 subscriptions and 0 schedules
10.1.2022, 21:14:17.084	[error]: javascript.0 (1034) script.js.Unwetterwarnungen_BETA: Error: Function "extendObject" is not allowed. Use adapter settings to allow it.
10.1.2022, 21:14:17.087	[error]: javascript.0 (1034)     at addWarncell (script.js.Unwetterwarnungen_BETA:3166:15)
10.1.2022, 21:14:17.087	[error]: javascript.0 (1034)     at init (script.js.Unwetterwarnungen_BETA:954:17)
`

**Comment by ticaki** [comment]
Hallo, du musst unter Instanzen in den Javascriptadapter Einstellungen  setObject erlauben

**Comment by monza258** [comment]
Super vielen Dank.

Bekomme leider noch einen Fehler. 

`
09:44:16.070 | error | javascript.0 (8703) script.js.Unwetterwarnungen_DWD: SyntaxError: Unexpected token o in JSON at position 1
-- | -- | --
09:44:16.073 | error | javascript.0 (8703) at addDatabaseData (script.js.Unwetterwarnungen_DWD:1613:19)
09:44:16.074 | error | javascript.0 (8703) at _helper (script.js.Unwetterwarnungen_DWD:1589:13)
09:44:16.074 | error | javascript.0 (8703) at InitDatabase (script.js.Unwetterwarnungen_DWD:1569:9)
09:44:16.075 | error | javascript.0 (8703) at changeMode (script.js.Unwetterwarnungen_DWD:562:9)
09:44:16.075 | error | javascript.0 (8703) at script.js.Unwetterwarnungen_DWD:640:19
09:44:16.075 | error | javascript.0 (8703) at script.js.Unwetterwarnungen_DWD:2375:3
`

**Comment by monza258** [comment]
Hi @ticaki, 

funktioniert so weit alles. Danke normal. Ich habe im Script das Warnlevel auf 3 gesetzt. Dennoch werden Frostwarnungen ab Stufe 1 versendet. Ist das eventuell ein Fehler? 

`
var minlevel                      =    3 // Warnungen unterhalb dieses Levels nicht senden; (DWD und Nina level 1-4  / UWZ 0-5)
var attentionWarningLevel         =    4 // Warnung gleich oder oberhalb dieses Levels mit zusätzlichen Hinweisen versehen
var minhoehe                      =    0 // Warnung für eine Höhe unterhalb dieses Wertes nicht senden
var maxhoehe                      =    5000 // Warnung für eine Höhe oberhalb dieses Wertes nicht senden
`

**Comment by ticaki** [comment]
Hallo,
minlevel betrifft automatisch versendete Warnungen. Wenn das automatisch versendet wird, dann ist es ein Fehler. Aber Einstellungen in den Objekten überschreiben IMMER einstellungen im Script ausser du setzt:

`var scriptOverrides = false;`

auf true
