### ISSUE TITLE
 Could not automatically create folder object 

### ISSUE THREAD

**Issue by Grothesk242** [ticaki/DWD-UWZ-NINA-Pushwarnungen-iobroker#20]
Schade:

```
 Could not automatically create folder object 0_userdata.0.wetterwarnung.alert.dwd.K-Rodenk.: The id "0_userdata.0.wetterwarnung.alert.dwd.K-Rodenk." is invalid. Ids are not allowed to end in "."
```
Kommt nur leider so vom dwd rüber. Kann man da nicht auf die Langversion gehen? Da wäre es nämlich 'Köln-Rodenkirchen' und wohl in Ordnung.

**Comment by ticaki** [comment]
Verstehe ich das richtig der . am ende kommt von DWD?

**Comment by Grothesk242** [comment]
Ja, ich hatte mir die ID für meinen Wohnort aus einer Excel-Datei von DWD herausgesucht. Da gab es zwei Spalten, eine mit den Langfassungen der Ortsnamen, eine mit den Kurzfassungen. Und die Kurzversion endet in meinem Fall mit einem Punkt.

**Comment by ticaki** [comment]
Erledigt, wollte es besser einbauen... aber bei mir geht keiner der Javascript reference seiten aktuell. Also nicht ändern der Quelle sonder den . entfernen. Dass kommt dann später, was ist wenn im Langnamen auch ein Punkt is z.B. St. für Sankt

**Comment by Grothesk242** [comment]
Der Pfad ist jetzt 
```
0_userdata.0.wetterwarnung.alert.dwd.K-Rodenk 
```
Also Punkt ist weg, die Quelle ist aber noch die Kurzform.

**Comment by ticaki** [comment]
Dann wird der Punkt wohl aus der Quelle entfernt worden sein.
